# Generated by Django 4.1.5 on 2023-01-04 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=11)),
                ('birth_date', models.DateField(null=True)),
                ('full_name', models.CharField(max_length=300, null=True)),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
